### ISSUE TITLE
Edit distance: use library

### ISSUE THREAD

**Issue by fcbr** [own-pt/cl-conllu#2]
I don't see a need to roll our own edit distance function.  There are plenty of libraries with a lot of different variants already available:

- https://github.com/mrkkrp/mk-string-metrics
- https://github.com/vsedach/vas-string-metrics

**Comment by arademaker** [comment]
indeed, I started with http://www.cliki.net/levenshtein. But it is restricted to strings and I needed to generalize to list of strings.

**Comment by arademaker** [comment]
See `utils.lisp`

**Comment by fcbr** [comment]
The reason for closing this issue is not clear to me: it was about using a library, but the referenced file contains an implementation instead of using a library, which is the exact opposite of what the issue was about.

Anyway, I'm fine closing this issue if there is no library that would help us here (strange, but we may have different requirements from them.)

**Comment by arademaker** [comment]
We don't use the libraries because the current implementation of `diff` does not make the distance of the sentences taken as a single string, but the distance of their list of the token's strings.  My first modification in the http://www.cliki.net/Levenshtein?v=5 code was to abstract the function used for the actuall test of similarities:

https://github.com/own-pt/cl-conllu/blob/master/utils.lisp#L24

Given that change, now I can use the `diff` function with two arrays instead of only two strings:

https://github.com/own-pt/bosque-UD/blob/master/scripts/mapping.lisp#L12-L19

Note that the `key` function returns the list of tokens `form`s in an array and the `test` function is the call of `distance` passing two arrays of strings:

https://github.com/own-pt/bosque-UD/blob/master/scripts/mapping.lisp#L12-L19

The actuall call for these functions is here:

https://github.com/own-pt/cl-conllu/blob/master/utils.lisp#L37-L40
